<?
    // Set page title.
    $this->headTitle($this->translate('Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headLink()->appendStylesheet('vendor/dataTables.bootstrap.css');
    $this->headLink()->appendStylesheet('vendor/font-awesome.min.css');
    

    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');

    $this->headScript()->appendFile('vendor/dataTables/jquery.dataTables.js');
    $this->headScript()->appendFile('vendor/dataTables/dataTables.bootstrap.js');    
?>


<div class="<?=$this->layoutClass('mainbody')?>">

   <div class="row"><br/></div>
   
   <h2><?=$this->transEsc('Record access by network')?></h2>

   <div class="row"><br/></div>

   <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i>Total</h3>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="clicks-line-chart"></div>
			    <div class="row"><br/><br/></div>
         		    <div class="table-responsive">
                                <table  class="table table-striped table-bordered table-hover" id="clicks-datatable">
                                    <thead/>
                                    <tbody/>
                                </table>
                            </div>
			    <div class="row"><br/><br/></div>
                            <div class="well">
                                <h4><?=$this->transEsc('About record access statistics')?></h4>
                                <p><?=$this->transEsc('about_record_access_statistics_text')?></p>
                            </div>

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
            </div>
            <!-- /.row -->
     
</div>


<script type="text/javascript">

var rawJson =  <?=json_encode($this->pivots) ?>;
var data = [];
var sources = {}

$.each( rawJson, function( key, value ) {
  var entry = {}
  
  entry['timestamp'] = key;

  $.each( value.pivot, function( i, pivot ) {
	entry[pivot.value] = pivot.count;
	sources[pivot.value] = "";

  });

  data.push(entry);
});


// Agregado de valores 0 a baches en la serie temporal 
$.each( data, function( index, row ) {
	$.each( sources, function( key, value ) {

		if ( typeof(row[key]) == "undefined" )
			row[key] = 0;		

	});
});

Morris.Line({
    element: 'clicks-line-chart',
    data: data,
    xkey: 'timestamp', 
    ykeys: Object.keys(sources),
    labels: Object.keys(sources),
    xLabels: 'month',
    pointSize: 2,
    smoth: 'false',
    hideHover: false,
    resize: true,
    yLabelFormat: function (y) { return y.toString() + ''; }
    
});



var columns = [];
columns.push({ 'data':'name', 'title':'<?=$this->transEsc('Network')?>' });

var timestamps = [];
$.each( data, function( key, value ) {
	timestamps.push(value["timestamp"]);
}); 
timestamps.sort();


$.each( timestamps, function( index, value ) {
	columns.push( {'data':value, 'title':value} );
}); 


var tData = {};

$.each( data, function( index, value ) {

	$.each( sources, function( network_name, empty ) {

		if ( tData[network_name] == null ) 
			 tData[network_name] = {}; 

		tData[network_name]["name"] = network_name;
		tData[network_name][ value["timestamp"] ] = value[network_name];
		
	}); 
}); 

var tDataArray = [];
$.each( tData, function( network_name, value ) {
	tDataArray.push( value );
});


$('#clicks-datatable').dataTable( {
    data: tDataArray,
    columns: columns,
    bFilter: false, 
    bInfo: false,
    bPaginate: false
} );   

</script>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("diretorioseer/menu.phtml")?>
</div>
