<?
    // Set page title.
    $this->headTitle($this->translate('Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headLink()->appendStylesheet('vendor/dataTables.bootstrap.css');
    $this->headLink()->appendStylesheet('vendor/font-awesome.min.css');
    

    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');

    $this->headScript()->appendFile('vendor/dataTables/jquery.dataTables.js');
    $this->headScript()->appendFile('vendor/dataTables/dataTables.bootstrap.js');    
?>



<div class="<?=$this->layoutClass('mainbody')?>">

   <div class="row"><br/></div>
   
   <h2><?=$this->transEsc('Document count')?> <?=$this->transEsc('by')?> <?=$this->transEsc( $this->field.'_fieldname')?></h2>

   <div class="row"><br/></div>
   
   <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Total</h3>
                            </div>
                        <div class="panel-body">
                            <div id="main-donut-chart"></div>
			   				<div class="row"><br/><br/></div>
         		    		<div class="table-responsive">
                                <table  class="table table-striped table-bordered table-hover" id="main-datatable">
                                    <thead/>
                                    <tbody/>
                                </table>
                            </div>
			    			<div class="row"><br/><br/></div>
			    			
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
            </div>
            <!-- /.row -->
            
            
            <div class="row">
            
            <? $dataByNetwork = $this->data; ?>
			<? foreach ( $dataByNetwork["pivots"] as $network => $data): ?>
			    			
            
                <div class="col-lg-3">
               		<div class="panel panel-default">
                    	<div class="panel-heading">
                              <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> <?=$network?></h3>
                                
                         </div>
                         <div class="panel-body">
			    				<div id="<?=$network?>-donut-chart"></div>
                                <div class="text-right">
                            	<a href="/vufind/Search/Results?lookfor=network_name%3A<?=$network?>&type=AllFields">Ver registros <i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                         </div>
                         <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->                  
             	</div>
                <!-- /.col-lg-4 -->
                
             <? endforeach; ?>
                
             </div>
             <!-- /.row -->
             
             
                    
            
     
</div>





<script type="text/javascript">

var alldata =  <?=json_encode($this->data) ?>;

// este diccionario funciona como traductor
<? $transValues = array(); ?>	
<?foreach ($this->fieldvalues as $value):?>
	<?$transValues[$value] = $this->transEsc($value); ?>
<?endforeach;?>
var translator = <?=json_encode($transValues); ?>

// main chart
var data = alldata["fields"][<?=json_encode($this->field)?>].values;

// traducción de los valores
var transData = [];
$.each( data, function( index, value ) {
	value["label"] = translator[ value["label"] ];
	transData.push( value );
});

Morris.Donut({
    element: 'main-donut-chart',
    data: transData,
    resize: true,
    formatter : function (y, data) { return y; } 
});


// Datatable
var columns = [];
columns.push({ 'data':'label', 'title':'<?=$this->transEsc($this->field.'_fieldname')?>' });
columns.push({ 'data':'value', 'title':'<?=$this->transEsc('Document count')?>' });

$('#main-datatable').dataTable( {
    data: data,
    columns: columns,
    bFilter: false, 
    bInfo: false,
    bPaginate: false,
    order: [[ 1, "desc" ]]
} );   

// By Network itetation
$.each( alldata["pivots"], function( network, pivot ) {

	// Traducción de los valores
	transPivot = [];
	$.each( pivot.values, function( index, value ) {
		value["label"] = translator[ value["label"] ];
		transPivot.push( value );
	});

	Morris.Donut({
	    element: network + '-donut-chart',
	    data: transPivot,
	    resize: true,
	    formatter : function (y, data) { return y; } 
    
	});	
});

</script>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("diretorioseer/menu.phtml")?>
</div>
