<?
    // Set page title.
    $this->headTitle($this->translate('Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headLink()->appendStylesheet('vendor/dataTables.bootstrap.css');
    $this->headLink()->appendStylesheet('vendor/font-awesome.min.css');
    
    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');

    $this->headScript()->appendFile('vendor/dataTables/jquery.dataTables.js');
    $this->headScript()->appendFile('vendor/dataTables/dataTables.bootstrap.js');   

    $this->headScript()->appendFile('data.utils.js');
    
?>


<div class="<?=$this->layoutClass('mainbody')?>">

	<div class="row">
		<br />
	</div>
	
	
	<h2>
		<?=$this->transEsc('Medatada stats')?> - <?=$this->transEsc($this->networkAcronym)?>
	</h2>

	<div class="row">
		<br />
	</div>

	
	<? $dataByNetwork = $this->data; ?>
	
	<!--  ?=json_encode($this->data) ?-->
	
	<? foreach ( $dataByNetwork as $data): ?>
		
		<div class="row">
		
			<div class="col-lg-12">	
				<h3><?=$this->transEsc($data["statID"]);?></h3>
			</div>
		
			<div class="col-lg-12">	
				  
				  <table  class="table table-striped table-bordered table-hover" id="diagnose-dt-<?=$data["statID"];?>">
	                 <thead/>
	                 <tbody/>
	              </table>	
			
			</div>
			<!-- /.col-lg-8 -->
		</div>
		<!-- /.row -->
		
		<div class="row">
			<div class="col-lg-12">
				<h3>&nbsp;</h3>
			</div>			
		</div>
			
		<script type="text/javascript">
					
			var data = <?=$data["jsonData"];?>;
			
			var translateMap = { "Field" :  "<?=$this->transEsc('Field')?>" ,
								 "NonEmpty" :  "<?=$this->transEsc('NonEmpty')?>" ,
								 "Valid" :  "<?=$this->transEsc('Valid')?>" ,
								 "NonEmptyOverTotal" :  "<?=$this->transEsc('NonEmptyOverTotal')?>" ,
								 "ValidOverTotal" :  "<?=$this->transEsc('ValidOverTotal')?>" ,
			};		

			$('#diagnose-dt-<?=$data["statID"];?>').dataTable( {
			    data: JavaDT2JQueryDTData(data),
			    columns: JavaDT2JQueryDTColumns(data, translateMap),
			    bFilter: false, 
			    bInfo: false,
			    bPaginate: false
			} );   
		</script>
		
	<? endforeach; ?>
		
		
		<!-- >div class="row">
			<div class="col-lg-12">
		
				<div class="well">
								<h4><?=$this->transEsc('About harvesting statistics')?></h4>
								<p>
									<?=$this->transEsc('about_harvesting_statistics_text')?>
								</p>
				</div>
			
			</div>
			
		</div-->
		<!-- /.row -->
		


</div>

<div class="<?=$this->layoutClass('sidebar')?>">
	<?=$this->render("diretorioseer/diagnose_menu.phtml")?>
</div>
