<?
    // Set page title.
    $this->headTitle($this->translate('Statistics'));
    
    $this->headLink()->appendStylesheet('vendor/morris.css');
    $this->headLink()->appendStylesheet('vendor/dataTables.bootstrap.css');
    $this->headLink()->appendStylesheet('vendor/font-awesome.min.css');
    $this->headLink()->appendStylesheet('vendor/nv.d3.min.css');

    $this->headScript()->appendFile('vendor/morris/raphael.min.js');
    $this->headScript()->appendFile('vendor/morris/morris.min.js');
    $this->headScript()->appendFile('vendor/d3.min.js');
    $this->headScript()->appendFile('vendor/nv.d3.min.js');

    $this->headScript()->appendFile('vendor/dataTables/jquery.dataTables.js');
    $this->headScript()->appendFile('vendor/dataTables/dataTables.bootstrap.js');    
?>

<style>
<!--

-->

.row-centered {
    text-align:center;
}
.col-centered {
    display:inline-block;
    float:none;
    /* reset the text-align */
    text-align:left;
    /* inline-block space fix */
    margin-right:-4px;
}
</style>


 

<div class="<?=$this->layoutClass('widebody')?>">	

	<div class="row">
		<br />
	</div>
	
	<h2>
		<?=$this->transEsc('Last successful harvesting results')?>
	</h2>

	
	<div class="row">
		<br />
	</div>

	<div class="row">
	
		<div class="col-lg-6 col-md-3">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<div class="row" id="sudam-chart"></div>
				</div>
				<div class="panel-footer"></div>
			</div>
		</div>
	
		<div class="col-lg-6 col-md-3">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<div class="row" id="caribean-chart"></div>
				</div>
				<div class="panel-footer"></div>
			</div>
		</div>
		
		
		
		<div class="row row-centered">
		
		
			<div class="col-lg-11 col-centered">
		
				 <div class="table-responsive">
				 
				 				<table  class="table table-striped table-bordered table-hover" id="maps-datatable">
                                    <thead/>
                                    <tbody/>
                                </table>		
                                
                 </div>
				
			
			</div>
			
		</div>
		<!-- /.row -->
		


	</div>
	<!-- /.row -->
	
</div>
	


<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type="text/javascript">

<? $dataByNetwork = $this->data; ?>

var dataArray = [ ['<?=$this->transEsc('Country')?>', '<?=$this->transEsc('Document count')?>'], <? foreach ( $dataByNetwork["networks"] as $data): ?><?="['". $data["name"]."',".$data["validSize"]."],"?><? endforeach; ?>];

</script>

<script type="text/javascript">

	  /////////////////
      google.load("visualization", "1", {packages:["geochart"]});
      google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
    	var data = google.visualization.arrayToDataTable( dataArray );
        var options = { "region":"005",  "colorAxis": {colors: ['white', '#2262a9']} };
        var chart = new google.visualization.GeoChart(document.getElementById('sudam-chart'));
        chart.draw(data, options);
      }

</script>

<script type="text/javascript">

      ////////////////// 
      google.load("visualization", "1", {packages:["geochart"]});
      google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
    	var data = google.visualization.arrayToDataTable( dataArray );
        var options = { "region":"013", "colorAxis": {colors: ['white', '#2262a9']} };
        var chart = new google.visualization.GeoChart(document.getElementById('caribean-chart'));
        chart.draw(data, options);
      }

</script>


<script type="text/javascript">

      var columns = [{ 'data':'name', 'title':'<?=$this->transEsc('Network')?>'}, { 'data':'validSize', 'title':'<?=$this->transEsc('Valid records')?>'}, { 'data':'datestamp', 'title':'<?=$this->transEsc('Date')?>'}];
	  var data = <?=json_encode($dataByNetwork["networks"]); ?>
      
      
      /////////////////////
      $('#maps-datatable').dataTable( {
	    data: data ,
	    columns: columns,
	    bFilter: false, 
	    bInfo: false,
	    bPaginate: false
	  } );  

	  
</script>

